# Recurrent Neural Network

- RNN은 순서가 있는 데이터를 입력으로 받고, 같은 네트워크를 이용하여 변화하는 입력에 대한 출력을 얻어낸다.

- 음악, 자연어, 날씨, 주가 등의 시간의 흐름에 따라 변화하고 그 변화가 의미를 갖는 데이터

- RNN의 구조

![RNN Architecture](https://img1.daumcdn.net/thumb/R720x0.q80/?scode=mtistory2&fname=http%3A%2F%2Fcfile23.uf.tistory.com%2Fimage%2F2578204757AC186F2A70DC)

- 일반적인 DNN Architecture와 같이 입력 X를 받아서 출력 Y를 반환하는 것은 동일하지만, 되먹임 구조를 가지고있다.

- 하지만, 그림처럼 입력이 X0, X1, X2, ... 와 같이 변할 때, 같은 네트워크를 사용하여 출력 H0, H1, H2, ... 를 반환하고 있는 것을 볼 수 있다.

- 중요한 것은 출력 값이 다음 입력을 받을 때의 RNN 네트워크에 동일하게 전달되고 있다는 것.

- 입력과 출력의 길이에 제한이 없으며, 다양한 형태의 네트워크를 만드는 것이 가능하다.

![RNN의 다양한 형태](https://discuss.pytorch.org/uploads/default/6415da0424dd66f2f5b134709b92baa59e604c55)

- RNN의 다양한 형태

  - One to One
    
    - RNN
    
  - One to Many

    - Image Captioning

  - Many to One

    - Sentiment Classification

  - Many to Many

    - Machine Translation

    - Video Classification (Frame Level)

# RNN의 Layer

### Simple RNN

- RNN의 가장 간단한 형태의 레이어

- 아래 그림과 같으며, Activation Function으로 tanh를 사용한다.

![Simple RNN](https://miro.medium.com/max/1512/1*HRuDxU1i4JNu-Ywt88LnaQ.png)

![RNN의 수식](https://cdn-images-1.medium.com/max/1000/1*uubYiUNDmhmR5KOPdJKYtQ.png)


In [1]:
# Simple RNN은 keras에서 한줄 구현이 가능하다.
import tensorflow as tf

# return_sequences : 출력으로 시퀀스 전체를 출력할 것인가?
rnn1 = tf.keras.layers.SimpleRNN(units=1, activation='tanh', return_sequences=True)

In [4]:
import numpy as np
X = []
Y = []
for i in range(6):
  lst = list(range(i, i + 4))
  X.append(list(map(lambda c: [c/10], lst)))
  Y.append((i+4)/10)

X = np.array(X)
Y = np.array(Y)

for i in range(len(X)):
  print(X[i], Y[i])

[[0. ]
 [0.1]
 [0.2]
 [0.3]] 0.4
[[0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6
[[0.3]
 [0.4]
 [0.5]
 [0.6]] 0.7
[[0.4]
 [0.5]
 [0.6]
 [0.7]] 0.8
[[0.5]
 [0.6]
 [0.7]
 [0.8]] 0.9


In [5]:
# input_shape는 timesteps와 input_dim을 나타낸다.
# timesteps는 RNN이 입력에 대해 계산을 반복하는 횟수이고, input_dim은 입력 벡터의 크기를 나타낸다.
model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=10, return_sequences=False, input_shape=[4, 1]),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse')
model.summary()

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (None, 10)                120       
_________________________________________________________________
dense (Dense)                (None, 1)                 11        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [6]:
model.fit(X, Y, epochs=100, verbose=0)
print(model.predict(X))

[[0.4127834 ]
 [0.5335896 ]
 [0.6340742 ]
 [0.7141707 ]
 [0.77536106]
 [0.81967306]]


In [9]:
print(model.predict(np.array([[[1.3], [1.4], [1.5], [1.6]]])))
print(model.predict(np.array([[[-11.1], [-11.0], [-10.9], [-10.8]]])))

[[0.75223696]]
[[1.8784832]]


- SimpleRNN Layer는 빠르게 모델을 만들어볼 때는 유용할 수 있다.

- 하지만 실무에서는 SimpleRNN의 단점을 개선한 **LSTM**이나 **GRU** 레이어를 많이 쓴다.